const CONSTANTS = Object.freeze({
  MIN_PURCHASE_AMOUNT: 0,
  LOTTO_TICKET_PRICE: 1000,
  NO_INPUT: 0,
  SEPARATOR_COMMA: ",",

  LOTTO_NUMBER_MIN: 1,
  LOTTO_NUMBER_MAX: 45,
  LOTTO_NUMBER_COUNT: 6,

  FIRST_PLACE: 0,
  SECOND_PLACE: 1,
  THIRD_PLACE: 2,
  FOURTH_PLACE: 3,
  FIFTH_PLACE: 4,

  MATCH_COUNT_SIX: 6,
  MATCH_COUNT_FIVE: 5,
  MATCH_COUNT_FOUR: 4,
  MATCH_COUNT_THREE: 3,
});

export { CONSTANTS };
