import CONSTANT from "./costant";

const ERROR = Object.freeze({
  IS_NOT_DEVIDED: `[ERROR] ${CONSTANT.PURCHASE_UNIT.UNIT_OF_LOTTO}원 단위로 입력해주세요.`,
  SMALL_THAN_THOUSAND: `[ERROR] ${CONSTANT.PURCHASE_UNIT.UNIT_OF_LOTTO}원 이상 입력해주세요.`,
  INVALID_VALUE: '[ERROR] 숫자만 입력해주세요.',
  BLANK: '[ERROR] 값을 입력해주세요.',
  INVALID_RANGE_NUMBER: `[ERROR] ${CONSTANT.LOTTO_CANSTANT.MIN_LOTTO_NUMBER}~${CONSTANT.LOTTO_CANSTANT.MAX_LOTTO_NUMBER} 사이의 숫자를 입력해주세요.`,
  IS_NOT_INT: '[ERROR] 정수 값만 사용 가능합니다.',
  INVALID_NUMBER_COUNT: `[ERROR] ${CONSTANT.LOTTO_CANSTANT.LOTTO_LENGTH}개의 값만 넣어주세요.`,
  DUPLICATED_NUMBER: '[ERROR] 중복되는 값이 있습니다.',
});

export default ERROR;
