import * as CONFIG from './config.js';
import { INPUT_ERROR_MESSAGES, LOTTO_ERROR_MESSAGES, PRIZE_ERROR_MESSAGES } from './errorMessages.js';
import { MESSAGES, PRIZE_MESSAGES } from './messages.js';
import { MATCHES, RANKS, PRIZE } from './rank.js';

export { CONFIG, MESSAGES, PRIZE_MESSAGES, INPUT_ERROR_MESSAGES, LOTTO_ERROR_MESSAGES, PRIZE_ERROR_MESSAGES, MATCHES, RANKS, PRIZE };
