import { LOTTO_CONFIG } from './lottoConfig.js';
import { MESSAGES, PRIZE_MESSAGES } from './messages.js';
import { INPUT_ERROR_MESSAGES, LOTTO_ERROR_MESSAGES, PRIZE_ERROR_MESSAGES } from './errorMessages.js';

export { LOTTO_CONFIG, MESSAGES, PRIZE_MESSAGES, INPUT_ERROR_MESSAGES, LOTTO_ERROR_MESSAGES, PRIZE_ERROR_MESSAGES };
