const LOTTO_PRICE_UNIT = 1000;
const REQUIRED_WINNING_NUMBERS_COUNT = 6;
const LOTTO_NUMBER_MIN = 1;
const LOTTO_NUMBER_MAX = 45;
const LOTTO_STATISTICS_KEYS = Object.freeze({
  THREE: 'matchedThree',
  FOUR: 'matchedFour',
  FIVE: 'matchedFive',
  FIVE_AND_BONUS: 'matchedFiveAndBonus',
  SIX: 'matchedSix',
});
const LOTTO_PRIZES = Object.freeze({
  THREE: 5000,
  FOUR: 50000,
  FIVE: 1500000,
  FIVE_AND_BONUS: 30000000,
  SIX: 2000000000,
});
const PERCENT_MULTIPLIER = 100;
const DECIMAL_PLACES = 1;

export {
  LOTTO_PRICE_UNIT,
  REQUIRED_WINNING_NUMBERS_COUNT,
  LOTTO_NUMBER_MIN,
  LOTTO_NUMBER_MAX,
  LOTTO_STATISTICS_KEYS,
  LOTTO_PRIZES,
  PERCENT_MULTIPLIER,
  DECIMAL_PLACES,
};
