const LOTTO_PRICE_UNIT = 1000;
const REQUIRED_WINNING_NUMBERS_COUNT = 6;
const LOTTO_NUMBER_MIN = 1;
const LOTTO_NUMBER_MAX = 45;

export { LOTTO_PRICE_UNIT, REQUIRED_WINNING_NUMBERS_COUNT, LOTTO_NUMBER_MIN, LOTTO_NUMBER_MAX };
