const MAGICNUMBER = Object.freeze({
  MINIMUM_POSITIVE_NUMBER: 1,
  LOTTO_PRICE: 1000,
  STARTINCLUSIVE: 1,
  ENDINCLUSIVE: 45,
  LOTTO_NUMBER_COUNT: 6,
  SEPARATOR: ',',
});

export default MAGICNUMBER;
