const OUTPUT_MESSAGE = Object.freeze({
  PURCHASE_NUMBER: "개를 구매했습니다.",
  WINNING_STATISTICS: "\n당첨 통계\n---",

  WINNING_RESULT_MATCH_SIX_PRIZE: "6개 일치 (2,000,000,000원) - ",
  WINNING_RESULT_MATCH_FIVE_WITH_BONUS_PRIZE:
    "5개 일치, 보너스 볼 일치 (30,000,000원) - ",
  WINNING_RESULT_MATCH_FIVE_PRIZE: "5개 일치 (1,500,000원) - ",
  WINNING_RESULT_MATCH_FOUR_PRIZE: "4개 일치 (50,000원) - ",
  WINNING_RESULT_MATCH_THREE_PRIZE: "3개 일치 (5,000원) - ",

  PROFIT_RATE_PREFIX: "총 수익률은 ",
  PROFIT_RATE_SUFFIX: "%입니다.",
});

export { OUTPUT_MESSAGE };
