const ERROR_PREFIX="[ERROR]";
const INPUT_LOTTO_COUNT=6;
const LOTTO_COST=1000;

const PURCHASE_MESSAGE={
    INPUT_PURCHASE_COST:'구입금액을 입력해 주세요.\n',
    PURCHASE_AMOUNT:'개를 구입했습니다.'
}

const PURCHASE_ERROR_MESSAGE={
    IS_NOT_NUMBER:`${ERROR_PREFIX} 숫자를 입력해 주세요.`,
    INVALID_BLANK:`${ERROR_PREFIX} 공백은 허용되지 않습니다.`,
    IS_NOT_POSITIVE_NUMBER:`${ERROR_PREFIX} 양수만 입력해주세요.`,
    IS_NOT_MULTIPLE_OF_THOUSAND:`${ERROR_PREFIX} ${LOTTO_COST}으로 나누어떨어지는 수만 입력 가능합니다.`
}

const LOTTO_MESSAGE={
    INPUT_LOTTO_NUMBERS:'당첨 번호를 입력해 주세요.\n',
}

const LOTTO_ERROR_MESSAGE={
    INVALID_COUNT:`${ERROR_PREFIX} 로또 번호는 ${INPUT_LOTTO_COUNT}개여야 합니다.`
}

export {PURCHASE_MESSAGE, PURCHASE_ERROR_MESSAGE, LOTTO_MESSAGE, LOTTO_ERROR_MESSAGE}